<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.acanx.module</groupId>
        <artifactId>aha</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.acanx.module.aha</groupId>
    <artifactId>aha-desktop</artifactId>
    <name>AHA-Desktop</name>
    <description>桌面端（OpenJFX，0.1 占位，0.2 实现）</description>

    <dependencies>
        <dependency>
            <groupId>com.acanx.module.aha</groupId>
            <artifactId>aha-core</artifactId>
        </dependency>
    </dependencies>
</project>
