<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.acanx.module</groupId>
        <artifactId>aha</artifactId>
        <version>0.1.2</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.acanx.module.aha</groupId>
    <artifactId>aha-extension-api</artifactId>
    <name>AHA-Extension-API</name>
    <description>扩展契约、事件总线、扩展点</description>

    <dependencies>
        <dependency>
            <groupId>com.acanx.module.aha</groupId>
            <artifactId>aha-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
